AWSTemplateFormatVersion: '2010-09-09'
Description: This defines some architecture for ElastiCachce.

Parameters:
  Environment:
    Type: String
    Description: The environment to deploy to.
    AllowedValues:
      - staging
      - production

Mappings:
  Environment:
    staging:
      Team: Developers
      NodeType: cache.t3.small
      NodeCount: 1
    production:
      Team: Operations
      NodeType: cache.t3.large
      NodeCount: 2

Resources:
  MyVPC:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType: !FindInMap [ !Ref Environment, NodeType ]
      Engine: redis
      EngineVersion: 6.x
      NumCacheNodes: !FindInMap [ !Ref Environment, NodeCount ]
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Team
          Value: !FindInMap [ !Ref Environment, Team ]
